"""
Email Tool for AI Research Crew Pro

Provides email sending capabilities via SMTP
with HTML formatting, templates, and error handling.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Type, Optional
from pydantic import BaseModel, Field, EmailStr
from crewai.tools import BaseTool
import markdown

from app.config.settings import get_settings
from app.utils.logger import get_logger

logger = get_logger(__name__)


class EmailInput(BaseModel):
    """Input schema for email tool."""
    to_email: str = Field(
        ..., 
        description="Recipient email address"
    )
    subject: str = Field(
        ..., 
        description="Email subject line",
        min_length=1,
        max_length=200
    )
    body: str = Field(
        ..., 
        description="Email body content in Markdown format"
    )


# Professional HTML email template
EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        
        body {{
            font-family: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif;
            line-height: 1.8;
            color: #2d3748;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f7fafc;
        }}
        .container {{
            background-color: #ffffff;
            border-radius: 16px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.05);
            overflow: hidden;
            border: 1px solid rgba(0,0,0,0.05);
        }}
        .header {{
            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
            color: white;
            padding: 40px 30px;
            text-align: center;
        }}
        .header h1 {{
            margin: 0;
            font-size: 28px;
            font-weight: 700;
            letter-spacing: -0.5px;
            text-shadow: 0 2px 4px rgba(0,0,0,0.2);
        }}
        .header p {{
            margin: 10px 0 0;
            font-size: 16px;
            opacity: 0.9;
            font-weight: 500;
        }}
        .content {{
            padding: 40px 30px;
        }}
        h2 {{
            color: #2a5298;
            font-size: 22px;
            font-weight: 600;
            margin-top: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #edf2f7;
        }}
        h3 {{
            color: #4a5568;
            font-size: 18px;
            font-weight: 600;
            margin-top: 25px;
        }}
        p {{
            margin-bottom: 16px;
        }}
        ul, ol {{
            padding-left: 20px;
            margin-bottom: 20px;
        }}
        li {{
            margin-bottom: 8px;
            color: #4a5568;
        }}
        a {{
            color: #2a5298;
            text-decoration: none;
            font-weight: 500;
            border-bottom: 1px dotted #2a5298;
            transition: all 0.2s;
        }}
        a:hover {{
            color: #1e3c72;
            border-bottom: 1px solid #1e3c72;
        }}
        code {{
            background-color: #edf2f7;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', monospace;
            font-size: 0.9em;
            color: #c53030;
        }}
        blockquote {{
            border-left: 4px solid #2a5298;
            background-color: #f8fbff;
            padding: 15px 20px;
            margin: 20px 0;
            border-radius: 0 8px 8px 0;
            font-style: italic;
            color: #4a5568;
        }}
        strong {{
            color: #2d3748;
            font-weight: 600;
        }}
        .footer {{
            background-color: #f7fafc;
            padding: 30px;
            text-align: center;
            border-top: 1px solid #edf2f7;
        }}
        .footer p {{
            margin: 5px 0;
            font-size: 13px;
            color: #718096;
        }}
        .tag {{
            display: inline-block;
            padding: 4px 12px;
            background-color: rgba(255,255,255,0.2);
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
            margin-top: 10px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Prime Brief</h1>
            <span class="tag">EXECUTIVE SUMMARY</span>
            <p>{subject}</p>
        </div>
        <div class="content">
            {content}
        </div>
        <div class="footer">
            <p><strong>Generated by Prime Brief</strong></p>
            <p>Powered by Multi-Agent Artificial Intelligence • CrewAI • Gemini</p>
            <p style="margin-top: 15px; font-size: 11px; color: #a0aec0;">
                This automated report contains AI-synthesized information. Please verify critical facts.
            </p>
        </div>
    </div>
</body>
</html>
"""


class EmailTool(BaseTool):
    """
    Email sending tool using SMTP.
    
    Features:
    - Markdown to HTML conversion
    - Professional email templates
    - Comprehensive error handling
    """
    
    name: str = "Send Email"
    description: str = (
        "Send professional emails with research reports. "
        "Accepts Markdown content which will be converted to formatted HTML."
    )
    args_schema: Type[BaseModel] = EmailInput
    
    def _run(self, to_email: str, subject: str, body: str) -> str:
        """
        Send email using SMTP with HTML formatting.
        
        Args:
            to_email: Recipient email address.
            subject: Email subject line.
            body: Email body in Markdown format.
            
        Returns:
            Success or error message.
        """
        settings = get_settings()
        
        if not settings.email_user or not settings.email_pass:
            logger.error("Email credentials not configured")
            return "Email failed: Email credentials not configured"
        
        try:
            logger.info(f"Sending email to: {to_email}")
            
            # Convert Markdown to HTML
            html_content = markdown.markdown(
                body,
                extensions=['tables', 'fenced_code', 'nl2br']
            )
            
            # Apply template
            html_body = EMAIL_TEMPLATE.format(content=html_content)
            
            # Create message
            msg = MIMEMultipart("alternative")
            msg["From"] = settings.email_user
            msg["To"] = to_email
            msg["Subject"] = subject
            
            # Attach plain text version
            msg.attach(MIMEText(body, "plain"))
            
            # Attach HTML version
            msg.attach(MIMEText(html_body, "html"))
            
            # Send email
            with smtplib.SMTP(settings.smtp_server, settings.smtp_port) as server:
                server.starttls()
                server.login(settings.email_user, settings.email_pass)
                server.sendmail(
                    settings.email_user, 
                    to_email, 
                    msg.as_string()
                )
            
            logger.info(f"Email sent successfully to {to_email}")
            return f"Email sent successfully to {to_email}"
            
        except smtplib.SMTPAuthenticationError:
            logger.error("SMTP authentication failed")
            return (
                "Email failed: Authentication error. "
                "Please check your email credentials and ensure you're using an App Password."
            )
            
        except smtplib.SMTPRecipientsRefused:
            logger.error(f"Recipient refused: {to_email}")
            return f"Email failed: The recipient address '{to_email}' was rejected."
            
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {e}")
            return f"Email failed: SMTP error - {str(e)}"
            
        except Exception as e:
            logger.error(f"Unexpected error sending email: {e}")
            return f"Email failed: {str(e)}"


def create_email_tool() -> EmailTool:
    """
    Factory function to create a configured email tool.
    
    Returns:
        Configured EmailTool instance.
    """
    return EmailTool()
